### ISSUE TITLE
安装出现问题

### ISSUE THREAD

**Issue by tikshy** [xupingmao/xnote#18]
Ubuntu 运行python3 -m pip install -r config/requirements.txt
出现此问题：Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9_m2kqy4/psutil/
这个问题怎么解决呀

**Comment by xupingmao** [comment]
@tikshy 你用的python是哪个版本的？试一试douban的pip源
```
python3 -m pip install psutil -i https://pypi.doubanio.com/simple/
```
如果psutil实在无法安装可以跳过，把这一行从config/requirements.txt删除就可以了

**Comment by raindyi** [comment]
自定义插件，删除py文件后依然存在，且自定义插件名称无法修改，默认为我的插件XXXX-XX-XX

**Comment by xupingmao** [comment]
> 自定义插件，删除py文件后依然存在，且自定义插件名称无法修改，默认为我的插件XXXX-XX-XX

@raindyi 

1. 删除插件需要重启后生效
2. 插件的名称是通过代码中的`@title`来定义的，比如
```
...
# @author admin
# @version 1.0.0
# @category note
# @title 插件名称
# @description 插件描述
...
```
后续我会补充一个文档说明插件的规范
