### ISSUE TITLE
请问如何备份和恢复笔记？谢谢

### ISSUE THREAD

**Issue by marchingsnail** [xupingmao/xnote#24]
请问如何备份和恢复笔记？谢谢，找了找doc的目录结构，似乎没见到

**Comment by xupingmao** [comment]
http://localhost:1234/system/backup?p=db_backup_home
数据库管理里面有备份和导入功能。

备份
![image](https://github.com/xupingmao/xnote/assets/4858453/4fb15eeb-d28c-49ae-8775-d9066db18d00)

在文件管理里面打开备份的数据库就可以导入
![image](https://github.com/xupingmao/xnote/assets/4858453/85769946-78b8-4485-9eb7-ba538bd19a42)

**Comment by xupingmao** [comment]
上述方法是备份数据库，如果要备份和恢复全部文件直接拷贝data文件夹即可。
