### ISSUE TITLE
docker compose not working

### ISSUE THREAD

**Issue by weixingweixing** [xupingmao/xnote#28]
config/boot/boot.sae.properties:port = 5050

docker-compose.yml 
ports:
- 1234:1234
doesn't match which cause connection rejected.

It seems that config/boot/boot.sae.properties not replaced by boot.properties. 

project folder xnote should map to /home

**Comment by xupingmao** [comment]
The config is fixed, please note that the user config file name has changed to `boot.local.properties`. 
thank you~
