### ISSUE TITLE
搜索中文会报错

### ISSUE THREAD

**Issue by 1yndonn3u** [xupingmao/xnote#3]
Python | lib/web/webapi.py in _debugwrite, line 512
'ascii' codec can't encode characters in position 63-64: ordinal not in range(128)
GET http://localhost:1234/search/search

Python版本：
Python 2.7.15

**Comment by xupingmao** [comment]
应该是data目录包含了中文，目前对这方面支持不是很完善。
你可以先使用--data参数指定一个纯ASCII码组成的路径试试。这个问题我尽快修复。

**Comment by 1yndonn3u** [comment]
查了一下，没有data目录没有中文，看起来不是这个问题引起的。

**Comment by xupingmao** [comment]
@1yndonn3u data目录是默认创建的，你看下xnote是不是放在中文路径下。你可以加上启动参数试试有没有问题，比如
Windows: python app.py --data D:/xnote_data
Mac/Linux: python app.py --data ~/xnote_data

**Comment by 1yndonn3u** [comment]
>  ~/D/w/xnote   master > pwd
> /Users/xxxx/Documents/wiki/xnote

目录没有中文，使用了--data参数依旧会报错。

**Comment by xupingmao** [comment]
@1yndonn3u 能否贴下完整的错误栈？还有搜索的关键字
