### ISSUE TITLE
依赖包装不了 

### ISSUE THREAD

**Issue by autolzg** [xupingmao/xnote#4]
python3.7.2  win7 32位
依赖包装不了 
作为一个python新手.看不太懂错误信息 
错误信息如下 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Don't know how to compile leveldb for Windows!
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\A
DMINI~1\AppData\Local\Temp\pip-install-7qdbb_ec\leveldb\

**Comment by xupingmao** [comment]
windows可以忽略leveldb安装错误，代码中已经附带了dll和驱动。

**Comment by xupingmao** [comment]
windows专门提供了一个版本的依赖requirements.win.txt
