### ISSUE TITLE
启动错误 Python 3.7.4

### ISSUE THREAD

**Issue by G3792274** [xupingmao/xnote#5]
python -m pip install -r requirements.win.txt

![image](https://user-images.githubusercontent.com/19231863/65380803-23bb3080-dd16-11e9-8ee1-a7a5d823e617.png)

**Comment by xupingmao** [comment]
这里看起来是安装psutil失败了，psutil并不是强依赖的第三方库，你可以把它从requirements.win.txt里面去掉试试。
